GO
/****** FHQQ356703572 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE MOM_MOMCLAS (
 		MOMCLAS_ID  nvarchar(100) NOT NULL,
		FNUMBER nvarchar(100) DEFAULT NULL,
		FNAME nvarchar(50) DEFAULT NULL,
		FDATA nvarchar(32) DEFAULT NULL,
		FNUM int NOT NULL,
		FPIC numeric(11,2) NULL,
		FDIQU nvarchar(100) DEFAULT NULL,
		FYINCANG int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MOMCLAS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
