GO
/****** FHQQ356703572 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ZM_ALARM (
 		ALARM_ID  nvarchar(100) NOT NULL,
		LOOP_ID nvarchar(100) DEFAULT NULL,
		ALARM_CONTENT nvarchar(255) DEFAULT NULL,
		ALARM_TIME nvarchar(100) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[ALARM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
